### PR TITLE
UL2016 SS

### PR DESCRIPTION
**Pull request by jainshilpi**
These are the scales and smearing text file for UL2016: 
includes both pre and post-VFP eras. 
Presented by @neilSchroeder and @rchatter in PPD here:
https://indico.cern.ch/event/1009591/contributions/4245933/attachments/2196962/3714830/ul16_gainDependentScales.pdf

These files will be used in re-mini and nano. The related PR will be created.

### CODE REVIEW

**Comment by slava77** [comment]
assign reconstruction

since this is used in miniAOD workflows, it's worth to add the reconstruction signature to this package in general

**Comment by slava77** [comment]
+1

based on tests done with cms-sw/cmssw#33030

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
this only adds new data files so can be merged. @santocch any objections, can you please review and sign it?

**Comment by santocch** [comment]
+1

**Pull request merged**
