### PR TITLE
UL2018 scales and smearing correction files

### PR DESCRIPTION
**Pull request by jainshilpi**
These are scales and smearing files for e/gamma for UL2018

### CODE REVIEW

**Comment by mrodozov** [comment]
any cmssw PR to test with ?

**Comment by jainshilpi** [comment]
yes the PR is just created: 
https://github.com/cms-sw/cmssw/pull/31936

**Comment by mrodozov** [comment]
@slava77 there are 42 differences in comparison, would you check it please ?

**Comment by jainshilpi** [comment]
Differences are expected since these are new scale and smearing corrections. Validation plots can be seen here: https://shilpi-afs.web.cern.ch/shilpi-afs/13TeV/2020/SSvalidation/UL2018/19Oct/

**Comment by santocch** [comment]
+1

**Comment by mrodozov** [comment]
+externals
two new files. actual changes will be made in cmssw anyway

**Comment by jainshilpi** [comment]
We would need a back-port for UL2018 as was done for UL2017 (#30199). If its agreed, then I can go ahead and do a back-port.

**Pull request merged**
