### PR TITLE
UL 2017 scales and smearing txt files

### PR DESCRIPTION
**Pull request by jainshilpi**
Committing the UL 2017 scales and smearings text files.

### CODE REVIEW

**Comment by slava77** [comment]
assign reconstruction 
due to coupling to cms-sw/cmssw#29526

**Comment by slava77** [comment]
+1

since this just adds new files, the PR should be safe to merge as is.
Additionally, I tests with cms-sw/cmssw#29526, in workflows which actually use the new files, as described in https://github.com/cms-sw/cmssw/pull/29526#issuecomment-626103130

**Comment by smuzaffar** [comment]
+externals

**Comment by santocch** [comment]
+1

**Pull request merged**
