### PR TITLE
Fix for Legacy2016 Smearings

### PR DESCRIPTION
**Pull request by previsualconsent**
Discussed in #4

### CODE REVIEW

**Comment by slava77** [comment]
@Sam-Harper 
I just wanted to confirm that this is the only change we need to fix the smearing

**Comment by slava77** [comment]
I see that the file already present in CMSSW from #4 is changed in the same way in this PR.
The changes are in agreement with slide 6 in https://indico.cern.ch/event/697082/contributions/3018397/attachments/1656254/2651425/2018-05-25-EGM-ScalesSmearings.pdf (with more decimal points though).
So, this looks as expected.

The tests from https://github.com/cms-sw/cmsdist/pull/4036 should be applicable to changes from this PR as well.
https://github.com/cms-sw/cmsdist/pull/4036#issuecomment-392165233 shows that the jenkins tests pass with differences in wf 136.7611 (the 2016 re-miniAOD). All changes in this workflow are in slimmedPhotons and slimeedElectrons in userFloats, as expected.
So, I think that we can proceed with merging this PR and also the matching cmsdist PRs (after tests, if necessary to confirm the same changes)

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar we need a cmsdist entry for master corresponding to the PR, and a corresponding one in 9_4_X

**Comment by slava77** [comment]
@previsualconsent @Sam-Harper 
please comment on the apparently continuing updates of these external files.
Is this a work in progress and we should hold off the start of the 94X 2016 re-mini?

The last set of updates seems like a significant bugfix.
Is it certain that this is now the last of it?

**Comment by Sam-Harper** [comment]
Hi Slava, this was discovered today

This is a significant bug fix which meant that the MC didnt scale the uncertainties propagated to them. It slipped through my validation. 

This should be the last of them.

**Comment by previsualconsent** [comment]
Yes, I was unaware of a specific use case that is now covered by the latest two commits.

**Comment by slava77** [comment]
is another commit 5 mins ago the last one?


I think it's worth giving you ~8 hours to double/triple-check.

**Comment by Sam-Harper** [comment]
agreed!

**Comment by smuzaffar** [comment]
assign reconstruction
please sign it before we merge and update cmsdist

**Comment by slava77** [comment]
@Sam-Harper @previsualconsent 
I just wanted to check with you that the final double/triple-checks are complete and you do not expect to make more changes.
Please confirm.
Thank you.

**Comment by Sam-Harper** [comment]
We expect no more changes. The MC is correctly getting scale uncertainties with a central scale value of 1. Which means the changes we added worked.

**Comment by slava77** [comment]
+1

@smuzaffar @mrodozov 
please merge this.
We can then run the standard tests after https://github.com/cms-sw/cmsdist/pull/4036 (or an equivalent) is updated

**Pull request merged**
