### PR TITLE
Re reco2017

### PR DESCRIPTION
**Pull request by previsualconsent**
## For 2016:

Fixes small bug that kept smearings <2%

Also + Et dependent corrections. 

## 2017
2017 scales in FineEtaR9Gain
And smearings

### CODE REVIEW

**Comment by fabiocos** [comment]
@previsualconsent is this affecting also the reminiAOD 2017, besides the forthcoming reminiAOD 2016?

**Comment by mrodozov** [comment]
testing it here: https://github.com/cms-sw/cmsdist/pull/4036

**Comment by slava77** [comment]
@previsualconsent @Sam-Harper 
please clarify the plans for the files added with this PR. AFAIK, there is no CMSSW PR yet which would be using them.

- Current CMSSW uses Legacy2016_07Aug2017_FineEtaR9_v3_ele_unc. This PR added Legacy2016_07Aug2017_FineEtaR9Et_ele_unc without a version modifier. Shouldn't the new file have a "v4" name for some continuity or was the version name dropped for some other reason?
- For 2017, what is the relationship between ReRecoEOY2017_ele_unc_scales and Run2017_17Nov2017_v1_ele_unc? My guess is that both are referring to the same 17Nov2017 date in the data processing campaign. Shouldn't the new files be Run2017_17Nov2017_v2_ele_unc for some continuity in the names?

**Comment by Sam-Harper** [comment]
I have to admit, I wasnt aware of this PR being made till now. 

So we have a bug in the 2016 MC smearing which mainly effects eta>2.0 but its small. We briefly discussed it on friday with you @slava77 on friday via email and found out our window for fixing it is closed.  Its not super clear to me whether I even want the fix floating around, I have to see the impact. 

The other files are still in testing and were prematurely added. Now eventually we do want these in the release not to be run centrally but to make analysers lifes much easier. I agree they should be consistently named.

**Comment by slava77** [comment]
On 5/29/18 12:36 AM, Sam Harper wrote:
> I have to admit, I wasnt aware of this PR being made till now.
> 
> So we have a bug in the 2016 MC smearing which mainly effects eta>2.0
> but its small. We briefly discussed it on friday with you @slava77
> <https://github.com/slava77> on friday via email and found out our
> window for fixing it is closed. Its not super clear to me whether I even
> want the fix floating around, I have to see the impact.
> 
> The other files are still in testing and were prematurely added. Now
> eventually we do want these in the release not to be run centrally but
> to make analysers lifes much easier. I agree they should be consistently
> named.
> 
> —

So, it sounds like this PR better be broken up in pieces:
- a fix in Legacy2016_07Aug2017_FineEtaR9_v3_ele_unc_smearings
- (renamed) updates for the next versions.

I have misunderstood the scope of the discussion on Friday.
It seemed like the fix was found to be needed for both the 2017 and 2016
smearings.
I was partly confused with the ensuing PR(s) which included both 2016
and 2017 updates.

If the fix is indeed only for the 2016, then we should still be able to
have a fix in the 94X as well.
@fabiocos

**Comment by Sam-Harper** [comment]
Ah I should have been clearer it was just for 2016 legacy I want to slip a minor minor fix in if it wasnt too late. Technically theres probably a similar bug in 2017 (the max smearing value was limited to ~2%) but that boat has sailed and we have what we have.

@slava77 I agree with out to break up this PR. @previsualconsent could you do that? A PR with just a fix to the smearings with the same name and then a second PR later with the files with correct name (but hold off on that, I think we want to fix the 1 TeV issue)  

thanks

**Comment by slava77** [comment]
@smuzaffar @mrodozov 
I was looking for a revert button. (we have these in the cms-sw PRs)
Except for one file this PR will have to be redone.

**Comment by smuzaffar** [comment]
@slava77 , I see the revert button just above the https://github.com/cms-data/EgammaAnalysis-ElectronTools/pull/4#issuecomment-392052968 comment.  Do you see it? Should I revert it?

**Comment by slava77** [comment]
> @slava77 , I see the revert button just above the #4 (comment) comment. Do you see it? Should I revert it?

I do not see it.

Please revert this.

**Comment by smuzaffar** [comment]
OK reverted. 
Should I merge the reverted PR and you will create a new PR with the updated files?

**Comment by slava77** [comment]
>  Should I merge the reverted PR and you will create a new PR with the updated files?

yes, please.

**Comment by slava77** [comment]
@Sam-Harper @previsualconsent please clarify if you will be able to make the fix-only PR today/tomorrow.
Thank you.

**Comment by previsualconsent** [comment]
I made PR in #6. 

I will do separate PR for the updated scales when requested.

**Comment by slava77** [comment]
On 5/29/18 9:54 AM, Peter Hansen wrote:
> I made PR in #6
> <https://github.com/cms-data/EgammaAnalysis-ElectronTools/pull/6>.
> 
> I will do separate PR for the updated scales when requested.
> 
> —

thank you.

**Pull request merged**
