### PR TITLE
Replace buggy UL2016 energy correction data files & update UL2017/18 scale systematics prescription

### PR DESCRIPTION
**Pull request by SanghyunKo**
Updating UL2016 electron & photon energy correction data files (and clean-up old and buggy files), following the [CMS talk thread](https://cms-talk.web.cern.ch/t/issue-with-photons-with-1-5-eta-2-0-specific-to-2016prevfp-ul/44247) and in preparation for the potential Run2 ReMiniAOD-ReNanoAOD campaign future (previously, the latest correction files only existed in the private repo [[link](https://github.com/jainshilpi/EgammaAnalysis-ElectronTools/tree/ULSSfiles_correctScaleSysMC)]).

Also a new tag is needed (preferrably V00-03-02 or V00-04-00) to update the files fetched by the [cmsdist/data/cmsswdata.txt](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_14_2_X/master/data/cmsswdata.txt#L76). Once the new tag is created then a couple of more PRs will be followed in cmsdist and cmssw itself to complete the fix.

FYI @cms-sw/egamma-pog-l2 @afiqaize @RSalvatico

Edited on 26 Sep 2024: changes in 2017 & 2018 data files are responsible for the change in the energy scale systematic prescription (vary energy scale in data → vary energy scale in MC). Their impacts were checked and presented in the PPD general [[link](https://indico.cern.ch/event/1455675/#41-egm-pog-issue-in-2016preapv)].

### CODE REVIEW

**Comment by RSalvatico** [comment]
type egamma

**Comment by RSalvatico** [comment]
@cmsbuild, please test

**Comment by tvami** [comment]
> Also a new tag is needed

This will be done automatically by the bot after we merge this PR

**Comment by tvami** [comment]
I was actually worried about this for a different reason. Let's say somebody wants to do an apple to apple comparison in earlier UL CMSSW release, and they dont care about these IDs, then they'd wanna use the old and buggy files. So I think you should not delete the old files @SanghyunKo

**Comment by tvami** [comment]
Alternatively update the relvals to take the new IDs

**Comment by SanghyunKo** [comment]
Hi @tvami, thanks for the comment. However, I do not foresee the case in which we need to keep the bugged energy correction files.

To be clear, these files are only needed when re-doing the electron/photon energy scale & smearing correction. If people want to look into the energy distribution with bugged files, they can still check the NanoAODv9 files for UL2016. Even if someone wants to re-run the energy correction with bugged files, one can checkout the previous tag - those files are still in the old tag (but only not in the master). People who want to do this are supposed to know what they are doing, and it shouldn't be an issue for them.

For a similar reason, the CI is supposed to fail. I intentionally did this because I believe that the fact all workflows run smoothly with bugged files led us to this situation. There was an [official prescription](https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaUL2016To2018#Scale_and_smearing_corrections_f) for MiniAODv2, but it sneaked into the NanoAOD and became persistent since it just runs fine without crashing (and this couldn't be caught easily with typical validation workflows because only a tiny fraction of electrons & photons are affected by this). But of course, I can restore and keep the old files in the master if someone has a strong opinion.

Regarding the CI, this PR needs to be tested with cms-sw/cmssw#46046 (and vice versa) if we want to run the CI successfully (I remember there is a bot command to run the workflow with a certain PR that hasn't been merged yet).

**Comment by tvami** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/46046

**Comment by SanghyunKo** [comment]
(holding PR until we decide what to do with the changes in 2017 & 2018 correction files @RSalvatico @afiqaize)

**Comment by hqucms** [comment]
hold

**Comment by hqucms** [comment]
unhold

**Comment by tvami** [comment]
+1

**Comment by antoniovilela** [comment]
+1

**Comment by antoniovilela** [comment]
merge

**Comment by smuzaffar** [comment]
@SanghyunKo , this PR has removed some old buggy files ( https://github.com/cms-data/EgammaAnalysis-ElectronTools/pull/12/commits/ef558810272c4d5cf39f4c3f79e8c970a60a190e) where are still accessed by CMSSW_10_6_X release. 

Can you please either open cmssw PR to remove the access of deleted files or add those files back

[a] https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_10_6_X_2024-11-03-0000/pyRelValMatrixLogs/run/136.72411_RunJetHT2016B_reminiaodUL+RunJetHT2016B_reminiaodUL+REMINIAOD_data2016UL_HIPM+HARVESTDR2_REMINIAOD_data2016UL_HIPM/step2_RunJetHT2016B_reminiaodUL+RunJetHT2016B_reminiaodUL+REMINIAOD_data2016UL_HIPM+HARVESTDR2_REMINIAOD_data2016UL_HIPM.log#/
```
----- Begin Fatal Exception 03-Nov-2024 07:26:47 CET-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=CalibratedElectronProducer label='calibratedElectrons'
Exception Message:
edm::FileInPath unable to find file EgammaAnalysis/ElectronTools/data/ScalesSmearings/Run2017_17Nov2017_v1_ele_unc_scales.dat anywhere in the search path.
The search path is defined by: CMSSW_SEARCH_PATH
${CMSSW_SEARCH_PATH} is: /data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_10_6_X_2024-11-03-0000/poison:/data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_10_6_X_2024-11-03-0000/src:/data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_10_6_X_2024-11-03-0000/external/slc7_amd64_gcc700/data:/cvmfs/cms-ib.cern.ch/sw/x86_64/week0/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2024-11-03-0000/src:/cvmfs/cms-ib.cern.ch/sw/x86_64/week0/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_X_2024-11-03-0000/external/slc7_amd64_gcc700/data
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_10_6_X_2024-11-03-0000/pyRelval/136.72411_RunJetHT2016B_reminiaodUL+RunJetHT2016B_reminiaodUL+REMINIAOD_data2016UL_HIPM+HARVESTDR2_REMINIAOD_data2016UL_HIPM
----- End Fatal Exception -------------------------------------------------
```

**Pull request merged**
