### PR TITLE
an update to scales and smearings files, specifically gain dependent scales for UL16 pre and post VFP datasets

### PR DESCRIPTION
**Pull request by neilSchroeder**

### CODE REVIEW

**Comment by slava77** [comment]
>  _No description provided._

- please provide some details for each file.
- are all of the files going to be used and which PR in cms-sw will use them (or when such PR will appear)
- please review the commit history and eliminate dead cycle commits which add and then remove some files

**Comment by rchatter** [comment]
> > _No description provided._
> 
>     * please provide some details for each file.
> 
>     * are all of the files going to be used and which PR in cms-sw will use them (or when such PR will appear)
> 
>     * please review the commit history and eliminate dead cycle commits which add and then remove some files

Hi Slava,

We withdraw this PR and will create a fresh one with a fixed commit history.
The details of the files and the relevant validation performed will also be provided.
But these are the residual electron/photon scale corrections for the UL16 Pre and Post VFP eras,
intended for use with these datasets.

Best,
Rajdeep for the EGM scales+smearings team

**Comment by slava77** [comment]
> But these are the residual electron/photon scale corrections for the UL16 Pre and Post VFP eras,
> intended for use with these datasets.

I could guess it for 4 files with Run2016_UltraLegacy_
in the name. My question was mostly about the other 8 files.

**Comment by jainshilpi** [comment]
Hi Slava,

About:
are all of the files going to be used and which PR in cms-sw will use them (or when such PR will appear)

The PR for using UL2016 will come soon together with adding this to nanoAOD. 

Thanks
Shilpi

**Comment by rchatter** [comment]
> > But these are the residual electron/photon scale corrections for the UL16 Pre and Post VFP eras,
> > intended for use with these datasets.
> 
> I could guess it for 4 files with Run2016_UltraLegacy_
> in the name. My question was mostly about the other 8 files.

Hi Slava,

Those other files are not relevant for the main repository. They are the same corrections for the different years but in an older format which is used with the H->GG analysis framework, which we hosted in our forks of this repo.

Pursuant to @jainshilpi 's message that these files would be committed afresh after the nanoAOD PR  @neilSchroeder can close this PR.

Thanks,
Rajdeep

**Pull request closed without merging**
