### PR TITLE
Legacy 2016 FineEtaR9

### PR DESCRIPTION
**Pull request by previsualconsent**
Discussed in https://indico.cern.ch/event/697080/#3-legacy-energy-scale-smearing

### CODE REVIEW

**Comment by smuzaffar** [comment]
assign analysis

**Comment by slava77** [comment]
@previsualconsent  @Sam-Harper 
considering one change after the submission and lack of comments about the updates, is this PR ready to go?

**Comment by previsualconsent** [comment]
Yes, as long as it is used with the updated EnergyScaleCorrection.cc in 
cms-sw/cmssw#22975

**Comment by slava77** [comment]
@smuzaffar 
this PR adds new files.
The content looks acceptable.
please merge

**Pull request merged**
