### PR TITLE
Revive back obsolete scale and smearing data files for 10_6_X backport

### PR DESCRIPTION
**Pull request by SanghyunKo**
Some IB test workflows in 10_6_X still have prelegacy modifiers and want to access the obsolete data files. This should fix the IB test failure seen in cms-sw/cmssw#46552 and cms-sw/cmssw#46595.

(Note: the tests will pass, but now it's the user's responsibility not to access the obsolete data files - in principle very few analysis teams want to re-nano with 10_6_X)

### CODE REVIEW

**Comment by tvami** [comment]
@cmsbuild please test

**Comment by smuzaffar** [comment]
Test parameters:
- full_cmssw = true
- relvals = 136.72411,136.7721,136.8311,1325.5,1325.7,11824.0,11825.0

**Comment by smuzaffar** [comment]
Please test for CMSSW_10_6_X

**Comment by smuzaffar** [comment]
Please test for CMSSW_10_6_X

**Comment by SanghyunKo** [comment]
Hmm... It doesn't seem like the test failure is related to this PR
```
>>> Created new campaign: mp27740
    - updated campaign list 'MP_ali_list.txt'
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_10_6_X_2024-11-03-0000/bin/slc7_amd64_gcc700/mps_setup_new_align.py", line 258, in <module>
    main()
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_10_6_X_2024-11-03-0000/bin/slc7_amd64_gcc700/mps_setup_new_align.py", line 102, in main
    copy_default_templates(args, next_campaign)
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_10_6_X_2024-11-03-0000/bin/slc7_amd64_gcc700/mps_setup_new_align.py", line 209, in copy_default_templates
    shutil.copy(os.path.join(default_conf_dir, f), next_campaign)
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc700/external/python/2.7.14-pafccj/lib/python2.7/shutil.py", line 133, in copy
    copyfile(src, dst)
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/testBuildDir/slc7_amd64_gcc700/external/python/2.7.14-pafccj/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'src/Alignment/MillePedeAlignmentAlgorithm/templates/universalConfigTemplate.py'

---> test test_MpsWorkFlow had ERRORS
 
^^^^ End Test test_MpsWorkFlow ^^^^
```

**Comment by smuzaffar** [comment]
+externals

unit test failure does not seem related to this update

**Pull request merged**
